### ISSUE TITLE
Prevent running view.remove() in the cleanup function or add note in docs

### ISSUE THREAD

**Issue by keller-mark** [manzt/anywidget#137]
I did not realize that the cleanup function runs during `view.remove()`. I added a view.remove() call within the cleanup function returned by render() and then this caused an infinite loop in my widget by accident.

It might be possible to prevent users from getting in this situation in some way, but I am not sure. Maybe instead of passing `this` to render, a different object could be passed without a `remove` property or with `remove()` somehow overridden as a no-op? 

https://github.com/manzt/anywidget/blob/8e589912f7a60989b90a5683a5a35a8a67456c08/packages/anywidget/src/widget.js#L174

If preventing it is not possible, the docs about the cleanup function could note that view.remove() should not be called inside the returned function, or could clarify that the cleanup function is run during `DOMWidgetView.remove`

**Comment by manzt** [comment]
Thanks for reporting! Do you think we could use a Proxy? Maybe patch `.remove()` as a no-op with a console.error to warning.
