### ISSUE TITLE
Support for webworkers?

### ISSUE THREAD

**Issue by saulshanabrook** [manzt/anywidget#335]
Is there support for adding a webworker script tag for the component? I am looking to add a tag like this `<script src="https://unpkg.com/@hpcc-js/wasm@2.13.1/dist/graphviz.umd.js" type="javascript/worker"></script>` to implement a [`d3-graphviz`](https://github.com/magjac/d3-graphviz) component.

**Comment by saulshanabrook** [comment]
Nevermind! I can create the webworker from JS.

**Comment by manzt** [comment]
Glad you found a solution! I don't believe `javascript/worker` is recognized mimetype by web-browsers. My understanding is that the `d3-graphviz` library uses this tag explicitly because the browser won't do anything with it, and then `d3-graphviz` looks for it on the page to create a web worker.

**Comment by saulshanabrook** [comment]
Yeah, I figured that out after opening this issue and then felt very silly! 

Thanks for making this library! I know the pain of writing widget libraries and this is perfect :)

**Comment by saulshanabrook** [comment]
For anyone else looking to use anywidget to render graphviz, I was able to get it working with the webworker by manually adding the script:

https://github.com/metadsl/egglog-python/blob/5d293a64efbb868bb04875702dc35d9619e633dc/python/egglog/graphviz_widget.py

https://github.com/metadsl/egglog-python/blob/5d293a64efbb868bb04875702dc35d9619e633dc/python/egglog/widget.js
