### ISSUE TITLE
Confusing error when Python package is missing JS files

### ISSUE THREAD

**Issue by kylebarron** [manzt/anywidget#344]
I moved deployment of my anywidget-based library from local to CI and forgot to build and include the relevant JS files. I got a confusing error mentioning regexes:

<img width="609" alt="image" src="https://github.com/manzt/anywidget/assets/15164633/09ff265a-e6c5-4cfe-a9b9-7262ba9e99c7">

Obviously the issue here is on my side, but if it's possible to have a more descriptive error here, that would be great!

**Comment by rgbkrk** [comment]
> What's a fast, geospatial skateboard? A lonboard.

Wow. I'm simultaneously groaning and loving your project name.
