### ISSUE TITLE
anywidget widgets not shown/displayed in jupyter notebook

### ISSUE THREAD

**Issue by AlcaArctica** [manzt/anywidget#353]
Hi, I found that I cannot display any widgets created with anywidget (I tried a few examples off the web). When I run the code it finishes without an error, however no widget appears, the output is just empty. Its not a general display issue, as widgets created with ipywidgets are indeed shown, as can be seen here:
<img width="780" alt="image" src="https://github.com/manzt/anywidget/assets/38464874/f393b1e2-6642-407a-980a-e4ba155fec77">
The same happens when I try to create widgets with other modules which depend on anywidget such as higlass.
I am new to jupyter so my set up might be wrong.
I installed the following in an empty conda env:

```
mamba create -n higlass-python
mamba activate higlass-python
mamba install python=3.11 # to install python3.11 (as otherwise aiohttp fails with python version 3.12)
pip install higlass-python
pip install ipykernel 
pip install clodius
pip install higlass-widget
pip install "anywidget[dev]"
pip install matplotlib
pip install ipympl
```

I am then starting a remote jupyter notebook on our HPC from within this environment with `jupyter notebook --no-browser --port=8889` and open the notebook locally on my laptop. I also choose the correct kernel (as otherwise I get the "modules not found" errors).
Any idea what is happening? Perhaps I need to enable anywidgets or similar?

**Comment by manzt** [comment]
Interesting. I wonder if something is happening with the notebook build. Could you try using JupyterLab for the time being? I’ll try to have a look into this today.

**Comment by AlcaArctica** [comment]
It is indeed working in jupyter lab! Thank you. I can just use jupyter lab instead.

**Comment by manzt** [comment]
Thanks for reporting the bug! anywidget _should_ work in classic notebooks as well, so I'll try to sort it out. Thanks for your patience.

**Comment by manzt** [comment]
Actually, in your `higlass-python` environment, could you try running:

```sh
which jupyter-notebook
```

Following the above:

```
mamba create -n higlass-python
mamba activate higlass-python
mamba install python=3.11 # to install python3.11 (as otherwise aiohttp fails with python version 3.12)
pip install higlass-python
pip install ipykernel 
pip install clodius
pip install higlass-widget
pip install "anywidget[dev]"
pip install matplotlib
pip install ipympl
```

in a clean environement, I get:

```
# Jupyter command `jupyter-notebook` not found.
```

Which makes me think that you have a global Jupyter installed.

**Comment by AlcaArctica** [comment]
You are right, as I never installed jupyter notebook its actually using the system wide software!
```
which jupyter-notebook
/sw/bin/jupyter-notebook
jupyter-notebook --version
5.4.1
```
I am sorry, that was a real oversight on my side!

**Comment by manzt** [comment]
All good! Happy just happy it's not a bug on our end :)
