### ISSUE TITLE
Version issue on anywidget for Deno is back

### ISSUE THREAD

**Issue by rgbkrk** [manzt/anywidget#355]
![image](https://github.com/manzt/anywidget/assets/836375/afa66a43-817b-4e90-98ee-660cc04837e9)

```
Error: Module anywidget, version 0.0.1 is not registered, however,         0.7.0 is
```

**Comment by manzt** [comment]
Ahh! I'll try to have a look today. Thanks for reporting. This is surprising.

**Comment by manzt** [comment]
@rgbkrk do you know if this is happening after pip-install anywidget or using the install script?

**Comment by manzt** [comment]
Can you make sure that you are using a later version of `mod.ts` in your script?

```js
import { widget } from "https://deno.land/x/anywidget@0.0.4/mod.ts"
```

**Comment by manzt** [comment]
Is the `Symbol.for("Jupyter.display")` no longer evalutated automatically for an object in Jupyter? This is kind of unfortunate.

**Comment by rgbkrk** [comment]
> Is the `Symbol.for("Jupyter.display")` no longer evalutated automatically for an object in Jupyter? This is kind of unfortunate.

It should be. I'll dig in.

**Comment by rgbkrk** [comment]
It appears to be working well now. Note: I'm on commit `53248e9bb3123a1b684f3f9f744bb671dfa53bc1` (JSX & TSX support on `main`).

<img width="609" alt="image" src="https://github.com/manzt/anywidget/assets/836375/622b3b48-9f46-49ae-a818-a8ae9ca2ecc0">
