### ISSUE TITLE
Altair demo from medium article broken

### ISSUE THREAD

**Issue by penningavery** [manzt/anywidget#381]
Hi,

I tried the altair demo: https://blog.jupyter.org/anywidget-jupyter-widgets-made-easy-164eb2eae102
Including the colab demo: https://colab.research.google.com/gist/manzt/2b83d3461c40ac7b43fde29515cb8077/extending_altair_with_anywidget.ipynb#scrollTo=73484882-7670-4711-91ef-3a4c09945ae6

But the cell here fails/the control is not interactive:
![Screenshot (341)](https://github.com/manzt/anywidget/assets/16319594/6b247251-2402-4bed-8bb2-db279e58feb4)

The altair widget in the first interactive cell seems to work, so I'm not sure what's happening with the anywidget version.

I tried it on a local install and it failed there too. Note in both colab and my local install the counter demo works fine.

Looks like a very useful library, thanks!

**Comment by manzt** [comment]
Hi there, it seems there is a bug in the latest release of Vega. Until that is resolved, you'll need to update this cell:

```diff
import anywidget
import traitlets


class ChartWidget(anywidget.AnyWidget):
    _esm = """
--    import embed from "https://cdn.jsdelivr.net/npm/vega-embed@6/+esm";
 ++   import embed from "https://esm.sh/vega-embed@6?deps=vega@5.26.0";

    export async function render({ model, el }) {
        let spec = JSON.parse(model.get("spec"));
        let api = await embed(el, spec);
        api.view.addSignalListener(spec.params[0].name, (_, update) => {
            console.log(update);
            model.set("selection", update);
            model.save_changes();
        });
    }
    """
    spec = traitlets.Unicode().tag(sync=True)
    selection = traitlets.Dict().tag(sync=True)
```

**Comment by penningavery** [comment]
Hi,

Thanks very much for the quick response, the example is working for me now!

Cheers,

Avery
