### ISSUE TITLE
anywidget fails on Raspberry Pi.  model.save_changes gives a ReferenceError

### ISSUE THREAD

**Issue by mlamoureux** [manzt/anywidget#386]
Running the "CounterWidget" example as shown in the anywidget blog, fails on a Raspberry Pi. The Pi is is connected to a remote Jupyter server (2i2c.callysto.ca and hub.callysto.ca show the error), running Chromium browser. (Works fine on a Mac or Windows machine.)

The counter button works and increases the count with each count. But the python variable "count" is never updated, and an error message appears when function model.save_changes() is called.
 >> Uncaught ReferenceError: structuredClone is not defined
 >> at AnyModel.serialize, at AnyModel.sync, at AnyModel.save, at AnyModel.save_changes

**Comment by manzt** [comment]
Your chromium needs to be updated to a later version that supports [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

**Comment by mlamoureux** [comment]
Thanks! I upgraded to the new OS "bookworm" which include the new chromium. All i well.
