### ISSUE TITLE
Custom HTML tags in top level widget

### ISSUE THREAD

**Issue by asaboor-gh** [manzt/anywidget#403]
By default, we get a `div` as a top level HTML  element when a widget is rendered in frontend. `ipywidgets` allow having other than `div` tags as well with the help of `preinitialize` function in Backbone.js. So e.g. in case of `ipywidgets.Button` we have the following [code](https://github.com/jupyter-widgets/ipywidgets/blob/b2531796d414b0970f18050d6819d932417b9953/packages/controls/src/widget_button.ts#L157 
) on javascript side 
```javascript 
export class ButtonView ... 
    ...
    preinitialize() { // at same level as render function
        this.tagName = 'button'; 
    }
```

This way we get `button` as top level element instead of `div`, but it seems to be impossible in  current implementation of `anywidget`, because user's render function acts on an already initialized view (inside top render function, so preinitialize added by user can't really work) and we can't modify tag of HTML Element once it is created. The example of `CounterWidget` in documentation renders as
```html
<div...>
    <button... >... </button>
</div>
```
Is there still a possibility to have top level custom HTML tags instead of having them nested in a `div`? Such that `CounterWidget` may looks like as simple as
```html
<button... >... </button>
```

**Comment by manzt** [comment]
Apologies for the delay. 

> Is there still a possibility to have top level custom HTML tags instead of having them nested in a div?

We strip back the API in anywidget intentionally to decouple from BackboneJS and JQuery implementation details in Jupyter Widgets. I understand that the `preinitialize` method is more declarative, but in either case  a `button` element is created in JS (either via Backbone our user-land code in anywidget).
