### ISSUE TITLE
HMR disabled by default?

### ISSUE THREAD

**Issue by jtpio** [manzt/anywidget#448]
Trying out the latest `anywidget` with JupyterLab 4. It seems like the built-in HMR is disabled by default?

Steps to reproduce:

1. `mamba create -n test-anywidget python=3.11 nodejs=20 jupyterlab=4 -y`
2. `mamba activate test-anywidgets`
3. `npm create anywidget@latest`
4. Select default options
5. `npm i`
6. `npm run dev`
7. `python -m pip install -e .`
8. `jupyter lab --no-browser`

[anywidgets-test-hmr.webm](https://github.com/manzt/anywidget/assets/591645/7791dd55-549c-4775-8247-8056fc6735e4)

**Comment by jtpio** [comment]
Answering my own question: browsing the docs for hints led to this page which mentions the feature being "opt-in": 

https://anywidget.dev/blog/anywidget-02/#native-hot-module-replacement-hmr

This page also mentions the use of the `ANYWIDGET_HMR=1` environment variable: 

![image](https://github.com/manzt/anywidget/assets/591645/22900db6-d6af-416c-9107-300149b82408)

**Comment by jtpio** [comment]
Maybe we could update the docs to make this feature more visible, for example in the "Getting Started", which is likely to be the starting point for folks new to `anywidget`? https://anywidget.dev/en/getting-started/

The screencast is actually a demo of HMR, so it could be a good place to put a similar note about the use of the `ANYWIDGET_HMR` environment variable.

**Comment by manzt** [comment]
Thank you for clarifying in the docs! Yes, perfect place to have it.
