### ISSUE TITLE
How to use events in the View?

### ISSUE THREAD

**Issue by dou-du** [manzt/anywidget#477]
Hi,

Since the anywidget only has render function, is it possible to use the “events" function of the View? Thanks!

```javascript
var View = Backbone.View.extend({
  el: '#login',
  events: {
    'click': 'onClick'
  },
  onClick: function () {
    alert('click!');  
  },
  render: function () {
    this.$el.append('<h1>What!</h1>');
  }
});
```

**Comment by manzt** [comment]
Closing for now. Feel free to reopen if you don't feel your issue was appropriately addressed!
