### ISSUE TITLE
Open In Panel

### ISSUE THREAD

**Issue by psychemedia** [manzt/anywidget#530]
Is there a straightforward way of creating an `anywidget` wrapped widget in its own panel?

For example, if the widget is a chart object that you want to add layers by executing code in different cells, it might be useful to open the object into its own panel rather than in cell output.

I suppose a workaround is to open the  widget into cell output and then use Jupyterlab-sidecar (if that extension still works?) to "rip" the widget into a separate panel.

**Comment by manzt** [comment]
Hi there. Unfortunately, the idea of an output panel or area is managed by the Jupyter environment, and not something managed by anywidget itself. 

In JupyterLab, you can right click to the left of an output cell and select "Create new view for Output Cell" or use sidecar.

![image](https://github.com/manzt/anywidget/assets/24403730/7c978cf6-fc27-4b79-b071-e80cbb304ccb)

**Comment by psychemedia** [comment]
With sidecar regularly in a state of disrepair, another alternative might be [`ipylab`](https://github.com/jtpio/ipylab):

```python
%pip install -q ipylab

from ipylab import JupyterFrontEnd, Panel, SplitPanel

app = JupyterFrontEnd()
panel = Panel()
panel.children = [WIDGET]

# Open a new panel containing the widget:
app.shell.add(panel, 'main', { 'mode': 'split-right' })
```
