### ISSUE TITLE
TODO:  `_model_module_version` and `_view_module_version` should be `anywidget.__version__`

### ISSUE THREAD

**Issue by tlambert03** [manzt/anywidget#57]
TODO: Right now the anywidget frontend code and the python package are published together with the same version. So `_model_module_version` and `_view_module_version` should be `anywidget.__version__`

_Originally posted by @manzt in https://github.com/manzt/anywidget/pull/46#discussion_r1096560803_

**Comment by manzt** [comment]
oh I actually think this this got added to `_descriptor.py` already!
