### ISSUE TITLE
Citing anywidget

### ISSUE THREAD

**Issue by jakobtroidl** [manzt/anywidget#592]
Hi Trevor, do you have a doi I could use to start citing anywidget?

**Comment by manzt** [comment]
I will have an update on this in a couple of days :)

**Comment by manzt** [comment]
We have made two preprints available, submitted to JOSS and SciPy Proceedings 2024 respectively. 

[![status](https://joss.theoj.org/papers/b1884ec01c408cf3afdc8c2c0c3a52c9/status.svg)](https://joss.theoj.org/papers/b1884ec01c408cf3afdc8c2c0c3a52c9)

```bibtex
@misc{manzjoss2024,
 title={anywidget: reusable widgets for interactive analysis and visualization in computational notebooks},
 url={osf.io/tw9sg},
 DOI={10.31219/osf.io/tw9sg},
 publisher={OSF Preprints},
 author={Manz, Trevor and Abdennur, Nezar and Gehlenborg, Nils},
 year={2024},
 month={Jun}
}
```

[SciPy Proceedings 2024 Submission](https://github.com/scipy-conference/scipy_proceedings/pull/930)

```bibtex
@misc{manzscipy2024,
 title={Any notebook served: authoring and sharing reusable interactive widgets},
 url={osf.io/pyn7u},
 DOI={10.31219/osf.io/pyn7u},
 publisher={OSF Preprints},
 author={Manz, Trevor and Gehlenborg, Nils and Abdennur, Nezar},
 year={2024},
 month={Jun}
}
```

**Comment by jakobtroidl** [comment]
Fantastic. I will start citing those. Thanks for sharing.

**Comment by manzt** [comment]
The papers are now published! I have updated the references above.
