### ISSUE TITLE
WebGPU demo would be very impressive

### ISSUE THREAD

**Issue by MRYingLEE** [manzt/anywidget#716]
### Describe the problem

In one of your talks on anywidget, you once mentioned anywidget can bring webgpu to Python world. But it seems not trival to do so.

### Describe the proposed solution

It would be very impressive if you can provide such a kind of demo.

### Importance

nice to have

**Comment by manzt** [comment]
WebGPU was just stabilized last year, so many of the WebGPU examples online (using the low-level Web API) are out of date. I'm guessing most folks in the community will end up interfacing with WebGPU via libraries much like WebGL.

That said, I updated [an example](https://gist.github.com/manzt/f9d2aeb81c95701f392702de275346cd) I made with Conway's Game of Life with anywidget. It does not use any libraries and demonstrates direct use of the WebGPU web APIs for both compute and rendering pipelines.

https://github.com/user-attachments/assets/7a01e441-7869-4777-a93c-c0028b558d86
