### ISSUE TITLE
React error current is null.  Only happens when importing a library built with vite

### ISSUE THREAD

**Issue by paddymul** [manzt/anywidget#761]
### Describe the bug

When I import a library built on top of react "some-react-lib" built with vite, I get react js errors.

```
Uncaught TypeError: st.current is null
    useState blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    zG blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:68
    dd blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:6
```

I created my repository using `npm create anywidget@latest ` and choosing a react project.  Then I put another codebase in `packages/some-react-tsxlib`. some-react-tsxlib is built with vite.  All of this is in a minimally reproducable repo

### Reproduction

I made a minimally reproducable repo here https://github.com/paddymul/anywidget-react-starter
```
git clone
git@github.com:paddymul/anywidget-react-starter.git
cd anywidget-react-starter
git checkout feat/rechart-only
cd packages/some-react-tsxlib
npm install && npm build
cd ../..
npm install && npm build
jupyter lab example.ipynb
```

Note:
the above steps work on main.  in main some-react-tsxlib doesn't import any react libraries.  But it does use `useState` and other react functionality.

### Logs

```shell
old render 17 4 1e946579-cbe0-4371-bca7-f4b7f6fadacb:68:31641
TypeError: st.current is null
    useState blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    zG blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:68
    dd blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:6
    g1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    v1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    SA blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Wl blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Dp blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    p1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Sf blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    mf blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    mm blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    bm blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    O1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    P1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    A1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    <anonymous> blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
example.ipynb:13851:25
Uncaught TypeError: st.current is null
    useState blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    zG blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:68
    dd blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:6
    g1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    v1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    SA blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Wl blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Dp blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    p1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Sf blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    mf blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    mm blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    bm blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    O1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
    P1 blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:8
    Kt blob:http://localhost:8788/1e946579-cbe0-4371-bca7-f4b7f6fadacb:1
```
```


### System Info

```shell
System:
    OS: macOS 13.6.1
    CPU: (8) arm64 Apple M1
    Memory: 56.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.109
    Safari: 16.6
```

```
 git+ssh://git@github.com/paddymul/anywidget-react-starter.git@d75bae52c8afae77f6b703572a744c865b6e2196#egg=anyw2_react
anywidget==0.9.13
# Editable Git install with no remote (buckaroo_anywidget==0.0.0)
-e /Users/paddy/code/buckaroo-anywidget
jupyter-events @ file:///private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_db0avcjzq5/croot/jupyter_events_1718738111427/work
jupyter-lsp @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jupyter-lsp-meta_1707339967035/work
jupyter_client @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jupyter_client_1701803191601/work
jupyter_core @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_73nomeum4p/croot/jupyter_core_1718818302815/work
jupyter_server @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d1t69bk94b/croot/jupyter_server_1718827086930/work
jupyter_server_terminals @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jupyter_server_terminals_1701803399551/work
jupyterlab @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_a2d0br6r6g/croot/jupyterlab_1725895226942/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab_server @ file:///private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_f64fg3hglz/croot/jupyterlab_server_1725865356410/work
jupyterlab_widgets==3.0.13
notebook_shim @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/notebook-shim_1707340024494/work
```
```


### Severity

blocking all usage of anywidget

**Comment by paddymul** [comment]
I think the error is most likely in my vite setup.  my rollup config is here https://github.com/paddymul/anywidget-react-starter/blob/feat/rechart-only/packages/some-react-tsxlib/vite.config.ts

The other place causing the problem could be the library I'm importing - recharts.  https://github.com/recharts/recharts

I reviewed https://github.com/manzt/anywidget/issues/185 and
https://github.com/manzt/anywidget/pull/190

neither seemed to apply to the problem I am having

**Comment by manzt** [comment]
Hi @paddymul, thanks for sharing! Unfortunately, I wasn’t able to reproduce the issue on my end, as the steps didn’t seem to work as expected. For example:

```
❯ npm install && npm build
Unknown command: "build"
```

It’s possible there might be some discrepancy with the environment, node_modules, or switching between branches/packages. To rule this out, could you try freshly cloning the repository and running the steps yourself? 

Here’s what worked for me:

```sh
gh repo clone paddymul/anywidget-react-starter
git checkout feat/rechart-only
cd packages/some-react-tsxlib
npm install
npm run build
cd ../../
npm install
npm run build
uv run jupyter lab example.ipynb
```

<img width="643" alt="image" src="https://github.com/user-attachments/assets/e96ab837-5fc4-4f5c-932c-79c5e3b144ec" />


As an aside, I don't find Vite very useful preparing JavaScript _packages_. I usually have to fight against it to get something reasonable and much prefer using `tsc` or `esbuild`.

**Comment by paddymul** [comment]
Thanks for the response!

there was an error in my reproduction steps, it should have been `npm run build`, it also should have included `pip install -e ".[dev]"`

I was able to reproduce the screenshot you saw, without an obvious error.  I will try my more complex setups tomorrow and see if they function.


I am not at all tied to Vite.  What's your favorite esbuild tutorial or starter project for a react tsxlib project?

I do want a normal npm package for my library, and I'd like my anywidget based python package to just import it as simply as possible.  I don't want my full js codebase to hang off of PROJECT_ROOT/js .  I would like my full JS project to look as much as possible like a normal JS library.  That way I figure it will be easier for JS devs to understand and contribute.

**Comment by paddymul** [comment]
I am now able to properly import my full react library, with my existing vite build script.

I ran into a couple of other stale environments, and I will eventually work to figure those out, at least for myself, and when I do, I will file an issue or a PR with instrutctions on how to avoid the problem.

I looked into using esbuild for my react component library.  I found multiple half baked tutorials that were out of date.  I'm still open to using esbuild, or whatever is the best supported JS build coolness.  It seems that there are many tutorials for building an an app with react with whatever build tool, and very few for building a library, especially when you layer in TS/JSX, and CSS importing.
