### ISSUE TITLE
Different behaviors among Colab, Jupyter Lab, and VS Code

### ISSUE THREAD

**Issue by giswqs** [manzt/anywidget#89]
I am exploring the [maplibre](https://maplibre.org/maplibre-gl-js-docs/api/) library with anywidget. The following code works perfectly with Colab. Jupyter Lab can display the map, but the map size is always fixed no matter what `div.style.width` and `div.style.height` values. VS Code throws errors. Any advice?

```python
import anywidget
import traitlets

class MapWidget(anywidget.AnyWidget):
    _esm = """
    function loadScript(src) {
      return new Promise((resolve, reject) => {
        let script = Object.assign(document.createElement("script"), {
          type: "text/javascript",
          async: true,
          src: src,
        });
        script.addEventListener("load", resolve);
        script.addEventListener("error", reject);
        document.body.appendChild(script);
      });
    };
    
    await loadScript("https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js");
    
    export function render(view) {
      const div = document.createElement("div");
      div.style.width = "100%";
      div.style.height = "500px";
      
        var map = new maplibregl.Map({
        container: div,
        style: 'https://demotiles.maplibre.org/style.json', // stylesheet location
        center: [0, 20], // starting position [lng, lat]
        zoom: 2 // starting zoom
        });
      view.el.appendChild(div);
    }
    """
    # make sure to include styles
    _css = "https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css"
    token = traitlets.Unicode().tag(sync=True)

m = MapWidget()
m
```

Colab:
![image](https://user-images.githubusercontent.com/5016453/226122302-51fccffa-351e-4030-ac8f-7d5411cd9b55.png)

Jupyter Lab:
![image](https://user-images.githubusercontent.com/5016453/226122314-6f759c6a-fe1f-4ab9-8124-97a5260c1696.png)

VS Code:
![image](https://user-images.githubusercontent.com/5016453/226123781-d5f45bf9-475e-4a8b-8138-9788919ea1bc.png)

**Comment by manzt** [comment]
I don't believe this is an anywidget bug. JupyterLab and Google Colab are related to how the the output areas in the DOM that JupyterLab and Google Colab provide (i.e., the DOM Node `view.el`). This is not something that anywidget has control over, and the same results would occur if you created a custom Jupyter widget with one of the cookiecutter templates.

The VS Code issue seems to be with your Python environment, and likely `ipywidgets`. Can you create a fresh environment?

**Comment by manzt** [comment]
actually these errors in VS Code are just adding noise. The issue is that the `loadScript` fails to add `maplibregl` as a global in the VSCode context leading to a `ReferenceError` because it isn't defined and you try to access `maplibregl` in the render function.

I notice that `maplibregl` is on NPM. I'd suggest not using unpkg for this code and instead pick a modern CDN like [esm.sh](https://esm.sh/) which allow mirrors unpkg, but additionally compiles/translates non ESM JavaScript to ESM that's on npm. This means you can ditch the `loadScript` code and use a valid ESM import.

```python
import anywidget
import traitlets

class MapWidget(anywidget.AnyWidget):
    _esm = """
    import maplibregl from "https://esm.sh/maplibre-gl@2.4.0";

    export function render(view) {
      const div = document.createElement("div");
      div.style.width = "100%";
      div.style.height = "500px";

      var map = new maplibregl.Map({
        container: div,
        style: 'https://demotiles.maplibre.org/style.json', // stylesheet location
        center: [0, 20], // starting position [lng, lat]
        zoom: 2 // starting zoom
        });
      view.el.appendChild(div);
    }
    """
    _css = "https://esm.sh/maplibre-gl@2.4.0?css"
    token = traitlets.Unicode().tag(sync=True)

MapWidget()
```

**Comment by manzt** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/24403730/226145112-82b00f36-19af-414f-a07f-fb0c29d1dc05.png">

**Comment by giswqs** [comment]
@manzt Perfect! It works like a charm. Thank you. 

How do you find out if a JS library is included in [esm.sh](https://esm.sh/)? The [esm.sh](https://esm.sh/) site does not seem to provide any search functionality like NPM. For now, I simply enter https://esm.sh/maplibre-gl and it redirects to https://esm.sh/maplibre-gl@2.4.0, and add `?css` to get https://esm.sh/maplibre-gl@2.4.0?css. Is this the correct way?

**Comment by manzt** [comment]
Sorry for the delay in my response. esm.sh is a CDN that mirrors the npm registry, so packages that are on npm _should_ be available via esm.sh under `https://esm.sh/<package-name>`. (read: you should be able to look up a package on npm and at least try to request it from esm.sh). An easy way to check is to copy and paste the esm.sh url in the browser.

The "magic" of esm.sh is that it will try to transform any JS that **is not** valid ESM to be compatible. This means that packages that don't publish ESM to npm can still be used via `import` from esm.sh domain.

The other thing you mentioned is with regard to the REST api that esm.sh exposes for requesting specific assets or versions from the CDN. The URL esm.sh/maplibre-gl automatically links to the latest version. It is best practice to check in the version in your package, however if you scroll down on the esm.sh landing page there are a lot of details about how to request a specific semver range, for example. The `?css` is also described further down on the page, as a way to request styles.
