### ISSUE TITLE
ModuleNotFoundError: No module named 'watchfiles'

### ISSUE THREAD

**Issue by kolibril13** [manzt/anywidget#94]
Following the tutorial from https://anywidget.dev/en/jupyter-widgets-the-good-parts/ (installed with `pip install anywidget`
) will lead to an error because not all dependencies are installed:
`ModuleNotFoundError: No module named 'watchfiles'`
This can be easily fixed:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/44469195/227714861-6d9048a9-379e-40a1-ac69-b66db5ce9c22.png">

Maybe one can add the watchfiles to the pyproject.toml dependency file?
Or one can mention in the https://anywidget.dev/en/getting-started/ page, that one should install `pip install --upgrade "anywidget[dev]"
`

Thanks for this great package!

**Comment by manzt** [comment]
Updated the doc! I have chosen not to include `watchfiles` as a strict dependency because it's only utilized when using the live-reload behavior during development (read: only used by **anywidget** developers when creating a widget, not downstream users of the widget).

**Comment by kolibril13** [comment]
nice, thank you!
When I use the live-reload behavior with `watchfiles` during development, do I have to add the `read_text()` method before shipping a package to pypi?
` _esm = pathlib.Path("index.js").read_text()`
Or would I add the `watchfiles` package to the dependencies for my anywidget project?
