### ISSUE TITLE
Example tweaks at anywidget.dev

### ISSUE THREAD

**Issue by kolibril13** [manzt/anywidget#96]
The demo at https://anywidget.dev/ is quite cool!

Just a minor comment on the behavior of `counter.value` :

https://user-images.githubusercontent.com/44469195/227717497-fb748759-bc41-43d1-8285-96964151d399.mov

In Jupyter notebooks, the output of `counter.value` is static, so it won't update immediately, as the website indicates.

 

https://user-images.githubusercontent.com/44469195/227717578-bf25f17c-56d4-4aaa-a910-f6a4eb67757e.mov

This update will only happen after another cell execution.
Maybe this example at anywidget.dev can be tweaked in a way that this is also considered?
That would be amazing! 🚀

**Comment by manzt** [comment]
Ahh, good catch! It's kind of a hidden demo on the site, and I wasn't sure if anyone actually noticed it's interactive 😅. I just pushed an update, feel free to offer suggestions.

**Comment by kolibril13** [comment]
that's an amazing Easter egg, thanks for this super quick update 🤩
